### ISSUE TITLE
addon.json Not In Whitelist (Linux)

### ISSUE THREAD

**Issue by r000t** [garrynewman/gmad#15] opened 2015-03-07 10:38 UTC
Gmad on Linux will not create an addon, because a required file, addon.json, is not on the whitelist. Confirmed this by observing the list contained in AddonWhiteList.h

	/tmp/z2_additionalpoly/addon.json
		[Not allowed by whitelist]

**Comment by Bo98** [comment] 2015-03-07 11:04
Are you supplying the correct "-folder" parameter?

**Comment by r000t** [comment] 2015-03-07 11:06
I use `-folder /tmp/z2_additonalpoly/` both with and without the trailing slash. This folder contains two others, `materials` and `models`, as well as addon.json

**Comment by robotboy655** [comment] 2015-03-07 11:54
Are you using gmad from GMod or did you compile it yourself?

**Comment by r000t** [comment] 2015-03-08 00:28
I've tried using a version from someone's Gmod installation (gmad_linux doesn't exist in my SteamApps folder or any subfolders), and a version compiled using a git clone from last night. Similar results on both.

**Comment by robotboy655** [comment] 2015-03-08 16:03
Ok, this appears to be another problem caused by https://github.com/garrynewman/bootil, I will see if I can whip out a fix.

**Comment by robotboy655** [comment] 2015-03-08 16:32
Ok, I think I found the fix, but I will not be committing it until GMod update releases. ( In the next update gmad_linux is shipped with the game BTW )

**Comment by xDShot** [comment] 2015-03-19 13:07
I'm getting the same error on Linux. Used gmad_linux from bin folder, which is supplied since last update.
I think it still not fixed.

**Comment by robotboy655** [comment] 2015-03-19 13:57
I know you do, just wait for a fix.

**Comment by robotboy655** [comment] 2015-04-14 21:14
Please test whether this is fixed in Dev branch.
http://wiki.garrysmod.com/page/Dev_Branch

**Closed** 2015-04-15 17:30 UTC
